### ISSUE TITLE
[Submission] Pixelstep

### ISSUE THREAD

**Issue by AleD219** [Magisk-Modules-Repo/submission#148]
https://github.com/AleD219/pixelstep

**Comment by skittles9823** [comment]
Wew happy so see someone finally figured out how to make modules for other launchers lol. (Really surprised it took this long)

But accepting this would make it a tad confusing for users because of what's about to be released. Paphonb and I have been working on a universal version which can enable quickstep on any launcher that has the launcher3 pie commits and it doesn't even require a reflash. Once it's ready it'll replace the lawnstep module in the repo.

**Comment by AleD219** [comment]
Well, better late than never :D
I don't know if pixel launcher will be compatible, I hope yes
I'll use this module Until your release.
Thanks for your fast reply.

**Comment by skittles9823** [comment]
Yea pixel launcher will be compatible. It doesn't use a hardcoded list of launchers. It has an app which detects possible providers that call on the quickstep stuff so it'll be future proof if more launchers add support :D

**Comment by AleD219** [comment]
Very interesting! I'll wait it.
thanks and good work for the module.
