### ISSUE TITLE
 [Submission] Anjali Old Lipi for Malayalam

### ISSUE THREAD

**Issue by jishnu7** [Magisk-Modules-Repo/submission#246]
https://github.com/jishnu7/Magisk-AnjaliOldLipi

**Comment by Didgeridoohan** [comment]
You might have noticed I rejected all your submitted font modules. I did this because you submitted them as separate modules. If you want to resubmit, please make a single module that includes all fonts and make it optional for the user which one to install.

This can be done with the [Unity module template](https://forum.xda-developers.com/android/software/module-audio-modification-library-t3579612) (with the volume key selector), by renaming the installation zip to match the desired font (only currently works when installing from recovery), by utilising a configuration file that the installation script detects, by having a separate ui script that installs with the module and can be run from a terminal emulator, etc, etc. There are several different ways to achieve this.

**Comment by jishnu7** [comment]
@Didgeridoohan Unity module, like you said, requires recovery - isn't the point of magisk manager to avoid that? If there is any other option which works on magisk manager, please let me know.

**Comment by Didgeridoohan** [comment]
You might want to read my message again...

Unity does not require to be installed through recovery. If you want to use the "rename the zip for different options" way of making a user pick different fonts the module would have to be installed through recovery (since currently the Magisk Manager renames the zip prior to installing). All other options I gave you work when installing from the Magisk Manager.

**Comment by jishnu7** [comment]
Thanks for the explanation. Sending unified module.
