### ISSUE TITLE
[Submission] Magisk Daemon Helper

### ISSUE THREAD

**Issue by Geofferey** [Magisk-Modules-Repo/submission#404]
https://github.com/Geofferey/mgkdhelper

**Comment by Geofferey** [comment]
What's up with this? Been sitting here 5 days now while I see others being rejected & accepted... Is there something wrong with the module or bot? I don't want to submit another if this is being ignored intentionally.

**Comment by Geofferey** [comment]
What's the point of bots and mods when neither can give a response?

**Comment by Didgeridoohan** [comment]
Submissions are reviewed whenever us moderators have time. I can only speak for myself, of course, but what I do is to do a quick first look. If I spot something right away I take action, otherwise I leave it until I have more time (a rare commodity) and that will vary depending on my first impression of the module in question.

5 days is nothing. We have a 3 week limit on submitted modules, so please be patient.

**Comment by Geofferey** [comment]
Thanks for that @Didgeridoohan. It would probably be helpful if you could leave a comment once you've seen a module & let us know it's pending review. I misguided in my assumption that the bot will automatically close the submission if there's something majorly flawed

**Comment by Didgeridoohan** [comment]
As soon as someone feels ready to take a look they will assign the module to themselves. That way you know someone is actually looking at it.

The bot will automatically close any submission that doesn't fulfill the basic requirements (wrong template, wrongly formatted module.prop, etc). The rest is up to us moderators.
