### ISSUE TITLE
[Submission] Moto Music App (Motorola Music)

### ISSUE THREAD

**Issue by dark-basic** [Magisk-Modules-Repo/submission#45]
https://github.com/dark-basic/MotoMusic

**Comment by sjayminsgithub** [comment]
@dark-basic Is there any benefit of systemizing this app ??

**Comment by JohnFawkes** [comment]
> @dark-basic Is there any benefit of systemizing this app ??

Hes not systemizing it. This would also be used on non moto devices

**Comment by OldMidnight** [comment]
My 2 cents: There are plenty of music apps on the play store, no need for one in the repo. I doubt there is a massive improvement in audio while using this app.

**Comment by JohnFawkes** [comment]
> My 2 cents: There are plenty of music apps on the play store, no need for one in the repo. I doubt there is a massive improvement in audio while using this app.

True but we have the Sony one on the repo so we can't deny him just because there's apps on the play store though

**Comment by dark-basic** [comment]
> True but we have the Sony one on the repo so we can't deny him just because there's apps on the play store though

It is true the sony music app is in the repository. and this app does not exist as such in the play store. And it was also modified so that it works in AOSP

**Comment by OldMidnight** [comment]
I didn't know that was there. If so, I think it should be removed, Miscellaneous apps that don't provide any more functionality than a regular play store app should be removed. Or soon we could have apps from every OEM under the sun plaguing the repo because another got through. On the other hand, Apps like V4A that offer functionality beyond what you would find in the play store and apps which provide an advanced feature set due to root presence should be encouraged

**Comment by dark-basic** [comment]
Good. the owner of the modification told me to close the thread. Seeing the problems to be able to publish it.

It is better to leave as archived
