### ISSUE TITLE
Remove Debload

### ISSUE THREAD

**Issue by cocka11** [Magisk-Modules-Repo/submission#858]
this scripts is for remove debload from all phone.

https://github.com/cocka11/Remove-Debload

**Comment by crok** [comment]
Hi,

I just looked through the code in the module and [[these]](https://github.com/cocka11/Remove-Debload/blob/main/system/bin/deblo#L12) two lines caught my eyes:

```
mount -o rw,remount /system 2>/dev/null
mount -o rw,remount /sbin/.magisk/block/system_root 2>/dev/null
```

This won't be approved I guess (it is against Magisk's systemless principle), and not even working on some new models at all (ex. where the /system partitions's file system is explicitly made to be read-only with the EXT4_FEATURE_RO_COMPAT_SHARED_BLOCKS flag ("super partition"), more info about it [here](https://android.stackexchange.com/questions/220892/system-partition-locked-to-read-only-in-android-10) and [here](https://lkml.org/lkml/2020/10/5/1039) for example).

**Comment by cocka11** [comment]
how to mount the system without those 2 lines. please help.

**Comment by crok** [comment]
I guess you are missing why Magisk is called "**Magi**c ma**sk**" and what "systemlessly operating" is meaning. You don't ever mount /system RW and modify it because that instantly breaks SafetyNet and everything (if it's even possible to mount it RW as I mentioned it is not always possible). If you want to modify anything on /system you mask it with Magisk's [magic mount](https://topjohnwu.github.io/Magisk/details.html#magic-mount)ing. I recommend to you to read through the [documentation](https://topjohnwu.github.io/Magisk/), especially the [Internal Details](https://topjohnwu.github.io/Magisk/details.html) and the [Developer Guides](https://topjohnwu.github.io/Magisk/guides.html). Anyway, [there's a debloater module in the repo already](https://github.com/Magisk-Modules-Repo/terminal_debloater) which effectively zeroize the apps' APKs and everything you don't want or need - without pm commands, although the idea to disable apps with pm commands is good just there are many apps in Play Store / F-Droid that does it in GUI. Others will `[fixme]` if I'm wrong but I guess I'm right..

**Comment by cocka11** [comment]
that debload that exists in the magsik only deletes the apk but not its
data or dalvik-cache while this script that I made deletes all the apk files

**Comment by crok** [comment]
> deletes all the apk files

... and exactly this is why it won't be approved IMO.

**Comment by cocka11** [comment]
🥺 my scripts is safe does not damage the device.

**Comment by LoganDark** [comment]
> 🥺 my scripts is safe does not damage the device.

It violates Magisk principles and probably won't be accepted into the official repository.

You are modifying /system instead of overlaying on it, and that is a big nono. Magisk modules must never modify /system. This will **permanently break** SafetyNet, and anyone who ever installs your module will never again be able to use apps like Netflix, Google Pay, Pokemon Go etc. even if they remove the module. They will have to completely reinstall their operating system, and then reinstall Magisk and everything. If they do not know your module is the culprit, they may never be able to get SafetyNet back.

You **are** damaging the device's integrity by modifying /system. If you want to submit your module here, please refactor it to use magic mounts instead, which is like modifying /system, but without breaking integrity checks.

Perhaps you should post a list of bloat apps on XDA instead, so users can use the existing debloat module to remove them. That way you will not be duplicating functionality, potentially incorrectly like done here

**Comment by cocka11** [comment]
I am using this module and SafetyNet is working very well without any
problems

**Comment by crok** [comment]
That's good but still it violates the most basic principles of Magisk. You can upload it to XDA and spread it from there but it won't be accepted in the official repo, I'm sure about that.

**Comment by LoganDark** [comment]
> You can upload it to XDA and spread it from there

If you do this, please do provide a warning that it permanently modifies /system
